[lib]
crate-type = ["lib", "staticlib"]

[package]
name = "ipio"
version = "0.1.0"
edition = "2024"

[build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
anyhow = "1.0.98"
bincode = { version = "2.0.1", features = ["derive"] }
libc = "0.2.172"
nanoid = "0.4.0"
swift-bridge = "0.1"
